---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  requiresafe:
    enabled: true
ratings:
  paths:
  - "**.scss"
  - "**.js"
exclude_paths:
- test/
- app/
- bin/
- ".github/"
- build/
- dist/
- docs/
- example/
- node_modules/
- ".git/"
- src/views/themes/default/css/
- src/views/themes/blank/css/
- src/views/themes/github/css/
